### ISSUE TITLE
Question about Docker

### ISSUE THREAD

**Issue by paulclifford** [RCOSDP/weko#2]
Hello, 

I'm not sure if this repo is intended to work out of the box, but when I try to launch it with a "docker-compose up" command, I get the following error:

"Service 'static' failed to build: The command '/bin/sh -c /code/scripts/create-instance.sh' returned a non-zero code: 1"

**Comment by fugokidi** [comment]
@paulclifford I tried to set it up. It worked, I could see Weko website with Top, Author Management, Workflow, Communities (the menu on the website). But I don't know how to upload the data.
Here is how I tried:
1. Checkout the develop branch
2. Follow the steps from INSTALL.rst (docker-compose stuff)
3. Access localhost:8001
You can log in with test01@hitachi.com, test02@hitachi.com and test03@hitachi.com with the password: uspass123.
Please share with me if you know how to upload the data to weko.

**Comment by paulclifford** [comment]
Thanks! That worked for me too. How did you set or figure out the password?

**Comment by fugokidi** [comment]
Yeah. I see 3 users are created from the `populate-instance.sh` with the `INVENIO_USER_PASS` which is from `Dockerfile` and `docker-compose.yml`.

**Comment by mhaya** [comment]
Thanks @fugokidi and @paulclifford. I'm preparing a short manual of WEKO3. Please wait a little.

**Comment by paulclifford** [comment]
A little manual would be really great, I can't figure out how to upload and display a simple item like a PDF.

**Comment by miroslavcapkovic** [comment]
Hello, 

my uploads go well, but save/publish or discard ends with three differents errors:

save: error 500 - 500 Failed to register item 
![image](https://user-images.githubusercontent.com/16556081/71257469-14a74700-2334-11ea-827a-c2d510fd3aaa.png)

publish: 404 The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. 
![image](https://user-images.githubusercontent.com/16556081/71257507-2be63480-2334-11ea-9e07-8c10f1542040.png)

and discard error: 405 The method is not allowed for the requested URL. 
![image](https://user-images.githubusercontent.com/16556081/71257541-3ef90480-2334-11ea-927f-fbbb4ab78dd1.png)

I have tried several branches and i am still stopping at the same error. 

Can u hint me , pls ?

Regards, MIro.

**Comment by mhaya** [comment]
Hi Miro,

I'm sorry for the inconvenience,  maybe I think you try to upload directly but the function will not be used in WEKO3. I wrote a brief tutorial including the depositing process( https://github.com/RCOSDP/weko/wiki/QuickStart ). Could you like to read and try it again?

Best regards, Masaharu.
