### ISSUE TITLE
A problem of administrator accounts

### ISSUE THREAD

**Issue by ties-makimura** [RCOSDP/weko#27]
Hello,

I installed WEKO3 in the following manual.
https://github.com/RCOSDP/weko/wiki/installation

However, I can't log in using administrator accounts such as test01@hitachi.com or info@inveniosoftware.org. and got the message , “Specified user does not exist”.

What's the solution to this problem?

**Comment by mhaya** [comment]
Did you run "populate-instance.sh" or did you get any error when running the script?
Currently, testing accounts are created by the script.
Creating account process in the script is here:
- https://github.com/RCOSDP/weko/blob/develop/scripts/populate-instance.sh#L284

**Comment by ties-makimura** [comment]
I ran the "'docker-compose exec web ./scripts/populate-instance.sh'" command and got the following error message on the screen.
 ```
 File "/home/invenio/.virtualenvs/invenio/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column cons.consrc does not exist
LINE 4:                 cons.consrc as src
                        ^
HINT:  Perhaps you meant to reference the column "cons.conkey" or the column "cons.conbin".
```

**Comment by mhaya** [comment]
What version of postgresql do you use?
I'm thinking you use postgresql version 12 from your error log. 

Currently, we are developing weko3 with postgresql 11.
So, if possible please use postgresql 11.

please change docker-compose.yml to fix postgresql version.
```
diff --git a/docker-compose.yml b/docker-compose.yml
index f4c1b0c55..2eb480bae 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -88,7 +88,7 @@ services:
       - "5001:5000"
   postgresql:
     restart: "always"
-    image: postgres
+    image: postgres:11
     environment:
       - POSTGRES_USER=invenio
       - POSTGRES_DB=invenio
```

**Comment by ties-makimura** [comment]
Thanks for your advice. it helped me solved my problem.
